### ISSUE TITLE
shipfactory dupes items/prints randomly/moneyprints without gold

### ISSUE THREAD

**Issue by zelrond** [StarLegacy/Issue-Tracker#129] opened 2020-08-29 20:10 UTC
yeah, that. shipfactory is printing in a random way. It consumes or not your materials, it moneyprinted a lot without gold slot and even with the materials loaded it doesnt print

**Comment by MicleBrick** [comment] 2020-08-30 04:14
duplicate of #70

**Closed by MicleBrick** 2020-08-30 04:14 UTC
