### ISSUE TITLE
Crafting Blasters/Power Tools creates dupes of the materials 

### ISSUE THREAD

**Issue by WatchmanPhileo** [StarLegacy/Issue-Tracker#237] opened 2020-10-17 21:05 UTC
When I was crafting blasters, chainsaws etc today for some reason the materials I was using were being duped and falling on the ground. I could easily pick them up and reuse them and literally was getting free items with extra ores to boot. Pretty serious issue needs to be fixed asap.

**Comment by Mr-CleanCreeper** [comment] 2020-10-19 04:27
I was able to reproduce this but when using full stacks of all items I was able to produce infinite amounts of crafting ingredients. Upon further testing and trying to delete the items using lava they do not despawn nor are they able to be deleted using lava.

**Comment by zelrond** [comment] 2020-10-21 11:58
Duplicate of
#195

**Closed as completed** 2020-10-21 14:55 UTC
Labels: duplicate
