### ISSUE TITLE
Update Issue - Machines Exploding

### ISSUE THREAD

**Issue by LeMaire69** [StarLegacy/Issue-Tracker#147] opened 2020-08-31 16:00 UTC
I looked in my autocrafter and it exploded. 

Also pipes aren't working again.

**Comment by zelrond** [comment] 2020-09-02 17:20
Pipes. Still not working. Confirmed

**Comment by MicleBrick** [comment] 2020-09-28 22:14
duplicate of https://github.com/StarLegacy/Issue-Tracker/issues/186 and https://github.com/StarLegacy/Issue-Tracker/issues/181

**Closed by MicleBrick** 2020-09-28 22:14 UTC
Labels: bug
