### ISSUE TITLE
Infinite resources dupe glitch. [BUG]

### ISSUE THREAD

**Issue by Mr-CleanCreeper** [StarLegacy/Issue-Tracker#240] opened 2020-10-19 05:39 UTC
**Describe the bug**

I am reposting this bug previously discovered by WatchmanPhileo due to its game breaking nature. This duplication glitch produces an infinite amount of the required crafting items. 
**To Reproduce**

Any custom item crafted with a full inventory will throw out the item along with an infinite amount of the items required to craft it. 
**Expected behavior**

When you craft an item with a full inventory you should drop the crafted item along with only the materials you had in the crafting menu.
**Screenshots**

**System (please complete the following information):**

- OS: [e.g. Windows]
- RAM: [e.g. 8gb RAM]
- Minecraft Version: [e.g. Minecraft Java Edition 1.16.3]
Windows 10
32Gb
1.16.3 Java
**Additional context**

This duplication glitch is game breaking. I was able to make a double chest of each precious material in under 10 minutes (I burned them with lava afterwards of course). I haven't tested it but I assume its automatable with hopper collection systems. This should be TOP priority.

**Comment by Mr-CleanCreeper** [comment] 2020-10-19 05:42
Forgot to mention the custom items created in the dupe do not despawn, but vanilla items do.

**Comment by zelrond** [comment] 2020-10-21 11:27
Duplicate of 
https://github.com/StarLegacy/Issue-Tracker/issues/195

**Closed as completed** 2020-10-21 14:53 UTC
Labels: bug, duplicate
